# bunnyhop-fila.yaml
apiVersion: rabbitmq.bruno.io/v1alpha1
kind: Queue
metadata:
  name: fila-notificacoes
spec:
  name: fila.notificacoes
  durable: true
  autoDelete: false
  arguments:
    x-message-ttl: 60000
