apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exchanges.rabbitmq.bruno.io
spec:
  group: rabbitmq.bruno.io
  names:
    plural: exchanges
    singular: exchange
    kind: Exchange
    shortNames:
      - rx
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                  enum: ["direct", "fanout", "topic", "headers"]
                durable:
                  type: boolean
                autoDelete:
                  type: boolean
              required: ["name", "type"]
      subresources:
        status: {}
