apiVersion: rabbitmq.bruno.io/v1alpha1
kind: Shovel
metadata:
  name: shovel-q2q
spec:
  sourceURI: amqp://guest:guest@localhost:5672/
  sourceQueue: fila.origem
  destinationURI: amqp://guest:guest@localhost:5672/
  destinationQueue: fila.destino2

---

apiVersion: rabbitmq.bruno.io/v1alpha1
kind: Shovel
metadata:
  name: shovel-e2q
spec:
  sourceURI: amqp://guest:guest@localhost:5672/
  sourceExchange: minha.exchange
  routingKey: notificacoes
  destinationURI: amqp://guest:guest@localhost:5672/
  destinationQueue: fila.destino
